language: cpp

dist: trusty

compiler: gcc

addons:
  apt:
    packages:
    - binutils-dev
    - libcurl4-openssl-dev
    - zlib1g-dev
    - libdw-dev
    - libiberty-dev
    - cmake
    - gcc
    - g++
    - make
    - python

script:
- bash -C ./kcov-appimage.sh

before_deploy:
- export AppImage=$(echo kcov*.AppImage)

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "${AppImage}"
  skip_cleanup: true
  on:
    all_branches: true
